//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEtapa2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignaturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asignaturas()
        {
            this.Literatura_Doc = new HashSet<Literatura_Doc>();
            this.Plan_tematico = new HashSet<Plan_tematico>();
            this.Prof_Asig = new HashSet<Prof_Asig>();
        }
    
        public int id_asignatura { get; set; }
        public string disciplina { get; set; }
        public string nombre_discip { get; set; }
        public string tipo_discip { get; set; }
        public string anio { get; set; }
        public string prerrequisito { get; set; }
        public string precedencia { get; set; }
        public string creditos { get; set; }
        public int horas { get; set; }
        public string frecuencia_semanal { get; set; }
        public string semestre { get; set; }
        public string descripcion { get; set; }
        public string recursos { get; set; }
        public string id_carrera { get; set; }
        public Nullable<int> id_plan_asignatura { get; set; }
    
        public virtual Carreras Carreras { get; set; }
        public virtual Plan_asignatura Plan_asignatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Literatura_Doc> Literatura_Doc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan_tematico> Plan_tematico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prof_Asig> Prof_Asig { get; set; }
    }
}
