//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEtapa2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public int id_doc { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha { get; set; }
        public string contenido { get; set; }
        public string observaciones { get; set; }
        public string objetivos { get; set; }
        public string documento { get; set; }
        public string locacion { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public System.DateTime fecha_e { get; set; }
        public int ID_G_A_P_A { get; set; }
        public string tipo { get; set; }
    
        public virtual Grupo_Asig_C_A Grupo_Asig_C_A { get; set; }
    }
}
