//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEtapa2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupos()
        {
            this.Grupo_Asig_C_A = new HashSet<Grupo_Asig_C_A>();
        }
    
        public int id_grupo { get; set; }
        public string anio { get; set; }
        public string nombre { get; set; }
        public string id_turno { get; set; }
        public int id_semestre { get; set; }
        public string id_carrera { get; set; }
    
        public virtual Carreras Carreras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupo_Asig_C_A> Grupo_Asig_C_A { get; set; }
        public virtual Semestre Semestre { get; set; }
        public virtual Turnos Turnos { get; set; }
    }
}
