//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEtapa2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public int id_horarios { get; set; }
        public Nullable<int> id_dia { get; set; }
        public Nullable<int> id_hora { get; set; }
        public string laboratorio { get; set; }
        public Nullable<int> ID_G_A_P_A { get; set; }
    
        public virtual Dia Dia { get; set; }
        public virtual Grupo_Asig_C_A Grupo_Asig_C_A { get; set; }
        public virtual Horas Horas { get; set; }
    }
}
