//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEtapa2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratorios
    {
        public string id_lab { get; set; }
        public string nombre_lab { get; set; }
        public string ubicacion { get; set; }
        public string id_carrera { get; set; }
    
        public virtual Carreras Carreras { get; set; }
    }
}
