//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEtapa2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Literatura_Doc
    {
        public int id_litdoc { get; set; }
        public string nombre_libro { get; set; }
        public string autor { get; set; }
        public string edicion { get; set; }
        public string anio { get; set; }
        public string presentacion_libro { get; set; }
        public Nullable<int> id_asignatura { get; set; }
    
        public virtual Asignaturas Asignaturas { get; set; }
    }
}
