//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEtapa2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int Id_noti { get; set; }
        public System.DateTime noti_fecha { get; set; }
        public string mensage { get; set; }
        public int valido { get; set; }
        public Nullable<int> id_documento_control { get; set; }
        public Nullable<int> IDPA { get; set; }
        public int IDUsuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
