//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEtapa2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prof_Asig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prof_Asig()
        {
            this.Grupo_Asig_C_A = new HashSet<Grupo_Asig_C_A>();
            this.PC = new HashSet<PC>();
            this.PDC = new HashSet<PDC>();
        }
    
        public int id_prof_asig { get; set; }
        public string horario_consulta { get; set; }
        public string hora_clase { get; set; }
        public string hora_cp { get; set; }
        public string hora_lab { get; set; }
        public string id_profesor { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> id_asignatura { get; set; }
    
        public virtual Asignaturas Asignaturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupo_Asig_C_A> Grupo_Asig_C_A { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC> PC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC> PDC { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
